// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5-DmTschEMX96SEUqGX0vqpniE2ES9_c',
    appId: '1:847187352008:web:5738953967df57197688fd',
    messagingSenderId: '847187352008',
    projectId: 'arogna',
    authDomain: 'arogna.firebaseapp.com',
    databaseURL: 'https://arogna-default-rtdb.firebaseio.com',
    storageBucket: 'arogna.firebasestorage.app',
    measurementId: 'G-R4VB154DNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAet2FHWRet09846W4B7xf45uDDt3AOFwM',
    appId: '1:847187352008:android:fa891909c1fa1a8c7688fd',
    messagingSenderId: '847187352008',
    projectId: 'arogna',
    databaseURL: 'https://arogna-default-rtdb.firebaseio.com',
    storageBucket: 'arogna.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ9BR008fr7Tyau5iosuEZ0T9QKwIEBLc',
    appId: '1:847187352008:ios:85e3c63c8cafcde77688fd',
    messagingSenderId: '847187352008',
    projectId: 'arogna',
    databaseURL: 'https://arogna-default-rtdb.firebaseio.com',
    storageBucket: 'arogna.firebasestorage.app',
    iosBundleId: 'com.example.arogna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ9BR008fr7Tyau5iosuEZ0T9QKwIEBLc',
    appId: '1:847187352008:ios:85e3c63c8cafcde77688fd',
    messagingSenderId: '847187352008',
    projectId: 'arogna',
    databaseURL: 'https://arogna-default-rtdb.firebaseio.com',
    storageBucket: 'arogna.firebasestorage.app',
    iosBundleId: 'com.example.arogna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5-DmTschEMX96SEUqGX0vqpniE2ES9_c',
    appId: '1:847187352008:web:8e3e961615093f437688fd',
    messagingSenderId: '847187352008',
    projectId: 'arogna',
    authDomain: 'arogna.firebaseapp.com',
    databaseURL: 'https://arogna-default-rtdb.firebaseio.com',
    storageBucket: 'arogna.firebasestorage.app',
    measurementId: 'G-TRCQ1328SK',
  );
}
